import type { NextRequest } from "next/server";

import { updateSession } from "@/lib/supabase/session";

/**
 * Runs before every matched request: refreshes the Supabase session cookie and
 * bounces anonymous visitors to /login.
 *
 * (Next 16 renamed this file convention from `middleware` to `proxy`.)
 */
export default async function proxy(request: NextRequest) {
  return updateSession(request);
}

export const config = {
  matcher: [
    /*
     * Everything except static assets and images. Keeping images and
     * _next/static out matters on mobile — otherwise every icon fetch would
     * trigger an auth round trip.
     *
     * `icon` and `apple-icon` are listed by name, not extension: they are
     * generated by app/icon.tsx and app/apple-icon.tsx and served from
     * extensionless URLs, so without this an installed home-screen app would
     * get a redirect to /login where it expected a PNG.
     */
    "/((?!_next/static|_next/image|favicon.ico|icon|apple-icon|manifest.webmanifest|.*\\.(?:svg|png|jpg|jpeg|gif|webp|ico)$).*)",
  ],
};
