-- ============================================================================
-- FIFA Score Tracker — team reference data
--
-- Run after 0001_init.sql. Safe to re-run: the (name, league) unique
-- constraint turns repeat runs into no-ops, and re-running picks up any teams
-- added to this file later.
--
-- The whole table is a few KB, so the client fetches it once and filters the
-- searchable dropdown in memory rather than hitting the network per keystroke.
-- short_name is what the mobile match cards render, falling back to name.
-- ============================================================================

insert into public.teams (name, short_name, league, country, is_national) values
  -- Premier League ----------------------------------------------------------
  ('Arsenal',                  'ARS', 'Premier League', 'England', false),
  ('Aston Villa',              'AVL', 'Premier League', 'England', false),
  ('Bournemouth',              'BOU', 'Premier League', 'England', false),
  ('Brentford',                'BRE', 'Premier League', 'England', false),
  ('Brighton & Hove Albion',   'BHA', 'Premier League', 'England', false),
  ('Chelsea',                  'CHE', 'Premier League', 'England', false),
  ('Crystal Palace',           'CRY', 'Premier League', 'England', false),
  ('Everton',                  'EVE', 'Premier League', 'England', false),
  ('Fulham',                   'FUL', 'Premier League', 'England', false),
  ('Ipswich Town',             'IPS', 'Premier League', 'England', false),
  ('Leicester City',           'LEI', 'Premier League', 'England', false),
  ('Liverpool',                'LIV', 'Premier League', 'England', false),
  ('Manchester City',          'MCI', 'Premier League', 'England', false),
  ('Manchester United',        'MUN', 'Premier League', 'England', false),
  ('Newcastle United',         'NEW', 'Premier League', 'England', false),
  ('Nottingham Forest',        'NFO', 'Premier League', 'England', false),
  ('Southampton',              'SOU', 'Premier League', 'England', false),
  ('Tottenham Hotspur',        'TOT', 'Premier League', 'England', false),
  ('West Ham United',          'WHU', 'Premier League', 'England', false),
  ('Wolverhampton Wanderers',  'WOL', 'Premier League', 'England', false),

  -- La Liga -----------------------------------------------------------------
  ('Alaves',                   'ALA', 'La Liga', 'Spain', false),
  ('Athletic Club',            'ATH', 'La Liga', 'Spain', false),
  ('Atletico Madrid',          'ATM', 'La Liga', 'Spain', false),
  ('Barcelona',                'BAR', 'La Liga', 'Spain', false),
  ('Celta Vigo',               'CEL', 'La Liga', 'Spain', false),
  ('Espanyol',                 'ESP', 'La Liga', 'Spain', false),
  ('Getafe',                   'GET', 'La Liga', 'Spain', false),
  ('Girona',                   'GIR', 'La Liga', 'Spain', false),
  ('Las Palmas',               'LPA', 'La Liga', 'Spain', false),
  ('Leganes',                  'LEG', 'La Liga', 'Spain', false),
  ('Mallorca',                 'MLL', 'La Liga', 'Spain', false),
  ('Osasuna',                  'OSA', 'La Liga', 'Spain', false),
  ('Rayo Vallecano',           'RAY', 'La Liga', 'Spain', false),
  ('Real Betis',               'BET', 'La Liga', 'Spain', false),
  ('Real Madrid',              'RMA', 'La Liga', 'Spain', false),
  ('Real Sociedad',            'RSO', 'La Liga', 'Spain', false),
  ('Sevilla',                  'SEV', 'La Liga', 'Spain', false),
  ('Valencia',                 'VAL', 'La Liga', 'Spain', false),
  ('Valladolid',               'VLL', 'La Liga', 'Spain', false),
  ('Villarreal',               'VIL', 'La Liga', 'Spain', false),

  -- Bundesliga --------------------------------------------------------------
  ('Augsburg',                 'FCA', 'Bundesliga', 'Germany', false),
  ('Bayer Leverkusen',         'B04', 'Bundesliga', 'Germany', false),
  ('Bayern Munich',            'FCB', 'Bundesliga', 'Germany', false),
  ('Bochum',                   'BOC', 'Bundesliga', 'Germany', false),
  ('Borussia Dortmund',        'BVB', 'Bundesliga', 'Germany', false),
  ('Borussia Monchengladbach', 'BMG', 'Bundesliga', 'Germany', false),
  ('Eintracht Frankfurt',      'SGE', 'Bundesliga', 'Germany', false),
  ('Freiburg',                 'SCF', 'Bundesliga', 'Germany', false),
  ('Heidenheim',               'FCH', 'Bundesliga', 'Germany', false),
  ('Hoffenheim',               'TSG', 'Bundesliga', 'Germany', false),
  ('Holstein Kiel',            'KIE', 'Bundesliga', 'Germany', false),
  ('Mainz 05',                 'M05', 'Bundesliga', 'Germany', false),
  ('RB Leipzig',               'RBL', 'Bundesliga', 'Germany', false),
  ('St. Pauli',                'STP', 'Bundesliga', 'Germany', false),
  ('Stuttgart',                'VFB', 'Bundesliga', 'Germany', false),
  ('Union Berlin',             'FCU', 'Bundesliga', 'Germany', false),
  ('Werder Bremen',            'SVW', 'Bundesliga', 'Germany', false),
  ('Wolfsburg',                'WOB', 'Bundesliga', 'Germany', false),

  -- Serie A -----------------------------------------------------------------
  ('Atalanta',                 'ATA', 'Serie A', 'Italy', false),
  ('Bologna',                  'BOL', 'Serie A', 'Italy', false),
  ('Cagliari',                 'CAG', 'Serie A', 'Italy', false),
  ('Como',                     'COM', 'Serie A', 'Italy', false),
  ('Empoli',                   'EMP', 'Serie A', 'Italy', false),
  ('Fiorentina',               'FIO', 'Serie A', 'Italy', false),
  ('Genoa',                    'GEN', 'Serie A', 'Italy', false),
  ('Hellas Verona',            'VER', 'Serie A', 'Italy', false),
  ('Inter',                    'INT', 'Serie A', 'Italy', false),
  ('Juventus',                 'JUV', 'Serie A', 'Italy', false),
  ('Lazio',                    'LAZ', 'Serie A', 'Italy', false),
  ('Lecce',                    'LEC', 'Serie A', 'Italy', false),
  ('AC Milan',                 'MIL', 'Serie A', 'Italy', false),
  ('Monza',                    'MON', 'Serie A', 'Italy', false),
  ('Napoli',                   'NAP', 'Serie A', 'Italy', false),
  ('Parma',                    'PAR', 'Serie A', 'Italy', false),
  ('Roma',                     'ROM', 'Serie A', 'Italy', false),
  ('Torino',                   'TOR', 'Serie A', 'Italy', false),
  ('Udinese',                  'UDI', 'Serie A', 'Italy', false),
  ('Venezia',                  'VEN', 'Serie A', 'Italy', false),

  -- Ligue 1 -----------------------------------------------------------------
  ('Angers',                   'SCO', 'Ligue 1', 'France', false),
  ('Auxerre',                  'AJA', 'Ligue 1', 'France', false),
  ('Brest',                    'BRS', 'Ligue 1', 'France', false),
  ('Le Havre',                 'HAC', 'Ligue 1', 'France', false),
  ('Lens',                     'RCL', 'Ligue 1', 'France', false),
  ('Lille',                    'LIL', 'Ligue 1', 'France', false),
  ('Lyon',                     'OL',  'Ligue 1', 'France', false),
  ('Marseille',                'OM',  'Ligue 1', 'France', false),
  ('Monaco',                   'ASM', 'Ligue 1', 'France', false),
  ('Montpellier',              'MHSC','Ligue 1', 'France', false),
  ('Nantes',                   'FCN', 'Ligue 1', 'France', false),
  ('Nice',                     'NIC', 'Ligue 1', 'France', false),
  ('Paris Saint-Germain',      'PSG', 'Ligue 1', 'France', false),
  ('Reims',                    'SDR', 'Ligue 1', 'France', false),
  ('Rennes',                   'SRFC','Ligue 1', 'France', false),
  ('Saint-Etienne',            'ASSE','Ligue 1', 'France', false),
  ('Strasbourg',               'RCSA','Ligue 1', 'France', false),
  ('Toulouse',                 'TFC', 'Ligue 1', 'France', false),

  -- Other UCL regulars ------------------------------------------------------
  ('Ajax',                     'AJX', 'Rest of Europe', 'Netherlands', false),
  ('PSV Eindhoven',            'PSV', 'Rest of Europe', 'Netherlands', false),
  ('Feyenoord',                'FEY', 'Rest of Europe', 'Netherlands', false),
  ('Benfica',                  'BEN', 'Rest of Europe', 'Portugal', false),
  ('Porto',                    'POR', 'Rest of Europe', 'Portugal', false),
  ('Sporting CP',              'SCP', 'Rest of Europe', 'Portugal', false),
  ('Celtic',                   'CEL', 'Rest of Europe', 'Scotland', false),
  ('Rangers',                  'RAN', 'Rest of Europe', 'Scotland', false),
  ('Galatasaray',              'GAL', 'Rest of Europe', 'Turkey', false),
  ('Fenerbahce',               'FEN', 'Rest of Europe', 'Turkey', false),
  ('Besiktas',                 'BJK', 'Rest of Europe', 'Turkey', false),
  ('Club Brugge',              'CLB', 'Rest of Europe', 'Belgium', false),
  ('Anderlecht',               'AND', 'Rest of Europe', 'Belgium', false),
  ('Red Bull Salzburg',        'RBS', 'Rest of Europe', 'Austria', false),
  ('Shakhtar Donetsk',         'SHK', 'Rest of Europe', 'Ukraine', false),
  ('Dynamo Kyiv',              'DYN', 'Rest of Europe', 'Ukraine', false),
  ('Slavia Prague',            'SLA', 'Rest of Europe', 'Czechia', false),
  ('Sparta Prague',            'SPA', 'Rest of Europe', 'Czechia', false),
  ('Olympiacos',               'OLY', 'Rest of Europe', 'Greece', false),
  ('Young Boys',               'YB',  'Rest of Europe', 'Switzerland', false),
  ('Copenhagen',               'FCK', 'Rest of Europe', 'Denmark', false),
  ('Malmo',                    'MFF', 'Rest of Europe', 'Sweden', false),

  -- National teams ----------------------------------------------------------
  ('Argentina',                'ARG', 'International', 'Argentina', true),
  ('Australia',                'AUS', 'International', 'Australia', true),
  ('Austria',                  'AUT', 'International', 'Austria', true),
  ('Belgium',                  'BEL', 'International', 'Belgium', true),
  ('Brazil',                   'BRA', 'International', 'Brazil', true),
  ('Cameroon',                 'CMR', 'International', 'Cameroon', true),
  ('Canada',                   'CAN', 'International', 'Canada', true),
  ('Chile',                    'CHI', 'International', 'Chile', true),
  ('Colombia',                 'COL', 'International', 'Colombia', true),
  ('Costa Rica',               'CRC', 'International', 'Costa Rica', true),
  ('Croatia',                  'CRO', 'International', 'Croatia', true),
  ('Czechia',                  'CZE', 'International', 'Czechia', true),
  ('Denmark',                  'DEN', 'International', 'Denmark', true),
  ('Ecuador',                  'ECU', 'International', 'Ecuador', true),
  ('Egypt',                    'EGY', 'International', 'Egypt', true),
  ('England',                  'ENG', 'International', 'England', true),
  ('France',                   'FRA', 'International', 'France', true),
  ('Germany',                  'GER', 'International', 'Germany', true),
  ('Ghana',                    'GHA', 'International', 'Ghana', true),
  ('Greece',                   'GRE', 'International', 'Greece', true),
  ('Hungary',                  'HUN', 'International', 'Hungary', true),
  ('Iceland',                  'ISL', 'International', 'Iceland', true),
  ('Italy',                    'ITA', 'International', 'Italy', true),
  ('Ivory Coast',              'CIV', 'International', 'Ivory Coast', true),
  ('Japan',                    'JPN', 'International', 'Japan', true),
  ('Mexico',                   'MEX', 'International', 'Mexico', true),
  ('Morocco',                  'MAR', 'International', 'Morocco', true),
  ('Netherlands',              'NED', 'International', 'Netherlands', true),
  ('Nigeria',                  'NGA', 'International', 'Nigeria', true),
  ('Norway',                   'NOR', 'International', 'Norway', true),
  ('Peru',                     'PER', 'International', 'Peru', true),
  ('Poland',                   'POL', 'International', 'Poland', true),
  ('Portugal',                 'POR', 'International', 'Portugal', true),
  ('Republic of Ireland',      'IRL', 'International', 'Ireland', true),
  ('Saudi Arabia',             'KSA', 'International', 'Saudi Arabia', true),
  ('Scotland',                 'SCO', 'International', 'Scotland', true),
  ('Senegal',                  'SEN', 'International', 'Senegal', true),
  ('Serbia',                   'SRB', 'International', 'Serbia', true),
  ('South Korea',              'KOR', 'International', 'South Korea', true),
  ('Spain',                    'ESP', 'International', 'Spain', true),
  ('Sweden',                   'SWE', 'International', 'Sweden', true),
  ('Switzerland',              'SUI', 'International', 'Switzerland', true),
  ('Turkey',                   'TUR', 'International', 'Turkey', true),
  ('Ukraine',                  'UKR', 'International', 'Ukraine', true),
  ('United States',            'USA', 'International', 'United States', true),
  ('Uruguay',                  'URU', 'International', 'Uruguay', true),
  ('Wales',                    'WAL', 'International', 'Wales', true)
on conflict (name, league) do update
  set short_name  = excluded.short_name,
      country     = excluded.country,
      is_national = excluded.is_national;
