-- ============================================================================
-- FIFA Score Tracker — team crest/badge images
--
-- Run after 0003_groups.sql. Safe to re-run: every statement is a plain
-- UPDATE keyed on the existing (name, league) unique constraint.
--
-- URLs are hotlinked from TheSportsDB (thesportsdb.com), fetched once by
-- scripts/fetch-team-logos.mjs. Re-run that script and re-paste this file if
-- a URL ever goes stale or a new team is added to 0002_seed_teams.sql.
-- ============================================================================

alter table public.teams add column if not exists logo_url text;

update public.teams set logo_url = 'https://r2.thesportsdb.com/images/media/team/badge/uyhbfe1612467038.png' where name = 'Arsenal' and league = 'Premier League';
update public.teams set logo_url = 'https://r2.thesportsdb.com/images/media/team/badge/cgvxt61785930389.png' where name = 'Aston Villa' and league = 'Premier League';
update public.teams set logo_url = 'https://r2.thesportsdb.com/images/media/team/badge/y08nak1534071116.png' where name = 'Bournemouth' and league = 'Premier League';
update public.teams set logo_url = 'https://r2.thesportsdb.com/images/media/team/badge/grv1aw1546453779.png' where name = 'Brentford' and league = 'Premier League';
update public.teams set logo_url = 'https://r2.thesportsdb.com/images/media/team/badge/ywypts1448810904.png' where name = 'Brighton & Hove Albion' and league = 'Premier League';
update public.teams set logo_url = 'https://r2.thesportsdb.com/images/media/team/badge/pbf4ul1782638263.png' where name = 'Chelsea' and league = 'Premier League';
update public.teams set logo_url = 'https://r2.thesportsdb.com/images/media/team/badge/ia6i3m1656014992.png' where name = 'Crystal Palace' and league = 'Premier League';
update public.teams set logo_url = 'https://r2.thesportsdb.com/images/media/team/badge/eqayrf1523184794.png' where name = 'Everton' and league = 'Premier League';
update public.teams set logo_url = 'https://r2.thesportsdb.com/images/media/team/badge/xwwvyt1448811086.png' where name = 'Fulham' and league = 'Premier League';
update public.teams set logo_url = 'https://r2.thesportsdb.com/images/media/team/badge/mdj1ey1634670785.png' where name = 'Ipswich Town' and league = 'Premier League';
update public.teams set logo_url = 'https://r2.thesportsdb.com/images/media/team/badge/xtxwtu1448813356.png' where name = 'Leicester City' and league = 'Premier League';
update public.teams set logo_url = 'https://r2.thesportsdb.com/images/media/team/badge/kfaher1737969724.png' where name = 'Liverpool' and league = 'Premier League';
update public.teams set logo_url = 'https://r2.thesportsdb.com/images/media/team/badge/vwpvry1467462651.png' where name = 'Manchester City' and league = 'Premier League';
update public.teams set logo_url = 'https://r2.thesportsdb.com/images/media/team/badge/xzqdr11517660252.png' where name = 'Manchester United' and league = 'Premier League';
update public.teams set logo_url = 'https://r2.thesportsdb.com/images/media/team/badge/lhwuiz1621593302.png' where name = 'Newcastle United' and league = 'Premier League';
-- Nottingham Forest: no confident free-tier match under any name variant
-- tried (see MANUAL_OVERRIDES in scripts/fetch-team-logos.mjs) — left
-- unset, TeamBadge falls back to initials.
update public.teams set logo_url = 'https://r2.thesportsdb.com/images/media/team/badge/ggqtd01621593274.png' where name = 'Southampton' and league = 'Premier League';
update public.teams set logo_url = 'https://r2.thesportsdb.com/images/media/team/badge/dfyfhl1604094109.png' where name = 'Tottenham Hotspur' and league = 'Premier League';
update public.teams set logo_url = 'https://r2.thesportsdb.com/images/media/team/badge/yutyxs1467459956.png' where name = 'West Ham United' and league = 'Premier League';
update public.teams set logo_url = 'https://r2.thesportsdb.com/images/media/team/badge/u9qr031621593327.png' where name = 'Wolverhampton Wanderers' and league = 'Premier League';
update public.teams set logo_url = 'https://r2.thesportsdb.com/images/media/team/badge/mfn99h1734673842.png' where name = 'Alaves' and league = 'La Liga';
update public.teams set logo_url = 'https://r2.thesportsdb.com/images/media/team/badge/68w7fe1639408210.png' where name = 'Athletic Club' and league = 'La Liga';
update public.teams set logo_url = 'https://r2.thesportsdb.com/images/media/team/badge/0ulh3q1719984315.png' where name = 'Atletico Madrid' and league = 'La Liga';
update public.teams set logo_url = 'https://r2.thesportsdb.com/images/media/team/badge/wq9sir1639406443.png' where name = 'Barcelona' and league = 'La Liga';
update public.teams set logo_url = 'https://r2.thesportsdb.com/images/media/team/badge/xfjtku1690436219.png' where name = 'Celta Vigo' and league = 'La Liga';
update public.teams set logo_url = 'https://r2.thesportsdb.com/images/media/team/badge/867nzz1681703222.png' where name = 'Espanyol' and league = 'La Liga';
update public.teams set logo_url = 'https://r2.thesportsdb.com/images/media/team/badge/eyh2891655594452.png' where name = 'Getafe' and league = 'La Liga';
update public.teams set logo_url = 'https://r2.thesportsdb.com/images/media/team/badge/kfu7zu1659897499.png' where name = 'Girona' and league = 'La Liga';
update public.teams set logo_url = 'https://r2.thesportsdb.com/images/media/team/badge/mmhyb11616443601.png' where name = 'Las Palmas' and league = 'La Liga';
update public.teams set logo_url = 'https://r2.thesportsdb.com/images/media/team/badge/tm0adr1616443898.png' where name = 'Leganes' and league = 'La Liga';
update public.teams set logo_url = 'https://r2.thesportsdb.com/images/media/team/badge/ssptsx1473503730.png' where name = 'Mallorca' and league = 'La Liga';
update public.teams set logo_url = 'https://r2.thesportsdb.com/images/media/team/badge/rvspvt1473502960.png' where name = 'Osasuna' and league = 'La Liga';
update public.teams set logo_url = 'https://r2.thesportsdb.com/images/media/team/badge/nzhu941655595465.png' where name = 'Rayo Vallecano' and league = 'La Liga';
update public.teams set logo_url = 'https://r2.thesportsdb.com/images/media/team/badge/2oqulv1663245386.png' where name = 'Real Betis' and league = 'La Liga';
update public.teams set logo_url = 'https://r2.thesportsdb.com/images/media/team/badge/vwvwrw1473502969.png' where name = 'Real Madrid' and league = 'La Liga';
update public.teams set logo_url = 'https://r2.thesportsdb.com/images/media/team/badge/vptvpr1473502986.png' where name = 'Real Sociedad' and league = 'La Liga';
update public.teams set logo_url = 'https://r2.thesportsdb.com/images/media/team/badge/vpsqqx1473502977.png' where name = 'Sevilla' and league = 'La Liga';
update public.teams set logo_url = 'https://r2.thesportsdb.com/images/media/team/badge/dm8l6o1655594864.png' where name = 'Valencia' and league = 'La Liga';
update public.teams set logo_url = 'https://r2.thesportsdb.com/images/media/team/badge/bnhu8b1719983736.png' where name = 'Valladolid' and league = 'La Liga';
update public.teams set logo_url = 'https://r2.thesportsdb.com/images/media/team/badge/vrypqy1473503073.png' where name = 'Villarreal' and league = 'La Liga';
update public.teams set logo_url = 'https://r2.thesportsdb.com/images/media/team/badge/xqyyvq1473453233.png' where name = 'Augsburg' and league = 'Bundesliga';
update public.teams set logo_url = 'https://r2.thesportsdb.com/images/media/team/badge/3x9k851726760113.png' where name = 'Bayer Leverkusen' and league = 'Bundesliga';
update public.teams set logo_url = 'https://r2.thesportsdb.com/images/media/team/badge/01ogkh1716960412.png' where name = 'Bayern Munich' and league = 'Bundesliga';
update public.teams set logo_url = 'https://r2.thesportsdb.com/images/media/team/badge/kag3jy1599821108.png' where name = 'Bochum' and league = 'Bundesliga';
update public.teams set logo_url = 'https://r2.thesportsdb.com/images/media/team/badge/tqo8ge1716960353.png' where name = 'Borussia Dortmund' and league = 'Bundesliga';
update public.teams set logo_url = 'https://r2.thesportsdb.com/images/media/team/badge/sysurw1473453380.png' where name = 'Borussia Monchengladbach' and league = 'Bundesliga';
update public.teams set logo_url = 'https://r2.thesportsdb.com/images/media/team/badge/rurwpy1473453269.png' where name = 'Eintracht Frankfurt' and league = 'Bundesliga';
update public.teams set logo_url = 'https://r2.thesportsdb.com/images/media/team/badge/urwtup1473453288.png' where name = 'Freiburg' and league = 'Bundesliga';
update public.teams set logo_url = 'https://r2.thesportsdb.com/images/media/team/badge/lbj7g01608236988.png' where name = 'Heidenheim' and league = 'Bundesliga';
update public.teams set logo_url = 'https://r2.thesportsdb.com/images/media/team/badge/9hwvb21621593919.png' where name = 'Hoffenheim' and league = 'Bundesliga';
update public.teams set logo_url = 'https://r2.thesportsdb.com/images/media/team/badge/1fpmgs1514394524.png' where name = 'Holstein Kiel' and league = 'Bundesliga';
update public.teams set logo_url = 'https://r2.thesportsdb.com/images/media/team/badge/fhm9v51552134916.png' where name = 'Mainz 05' and league = 'Bundesliga';
update public.teams set logo_url = 'https://r2.thesportsdb.com/images/media/team/badge/zjgapo1594244951.png' where name = 'RB Leipzig' and league = 'Bundesliga';
update public.teams set logo_url = 'https://r2.thesportsdb.com/images/media/team/badge/5qupxa1608237013.png' where name = 'St. Pauli' and league = 'Bundesliga';
update public.teams set logo_url = 'https://r2.thesportsdb.com/images/media/team/badge/yppyux1473454085.png' where name = 'Stuttgart' and league = 'Bundesliga';
update public.teams set logo_url = 'https://r2.thesportsdb.com/images/media/team/badge/q0o5001599679795.png' where name = 'Union Berlin' and league = 'Bundesliga';
update public.teams set logo_url = 'https://r2.thesportsdb.com/images/media/team/badge/tkvqan1716960454.png' where name = 'Werder Bremen' and league = 'Bundesliga';
update public.teams set logo_url = 'https://r2.thesportsdb.com/images/media/team/badge/ci9trv1778399557.png' where name = 'Wolfsburg' and league = 'Bundesliga';
update public.teams set logo_url = 'https://r2.thesportsdb.com/images/media/team/badge/qix5ku1780561327.png' where name = 'Atalanta' and league = 'Serie A';
update public.teams set logo_url = 'https://r2.thesportsdb.com/images/media/team/badge/2qi1u31655592366.png' where name = 'Bologna' and league = 'Serie A';
update public.teams set logo_url = 'https://r2.thesportsdb.com/images/media/team/badge/wvsvxt1447534471.png' where name = 'Cagliari' and league = 'Serie A';
update public.teams set logo_url = 'https://r2.thesportsdb.com/images/media/team/badge/02x81t1627405841.png' where name = 'Como' and league = 'Serie A';
update public.teams set logo_url = 'https://r2.thesportsdb.com/images/media/team/badge/c1ie6b1622561483.png' where name = 'Empoli' and league = 'Serie A';
update public.teams set logo_url = 'https://r2.thesportsdb.com/images/media/team/badge/hc8nhu1656098030.png' where name = 'Fiorentina' and league = 'Serie A';
update public.teams set logo_url = 'https://r2.thesportsdb.com/images/media/team/badge/52s8dn1655553600.png' where name = 'Genoa' and league = 'Serie A';
update public.teams set logo_url = 'https://r2.thesportsdb.com/images/media/team/badge/p6camf1593457737.png' where name = 'Hellas Verona' and league = 'Serie A';
update public.teams set logo_url = 'https://r2.thesportsdb.com/images/media/team/badge/ryhu6d1617113103.png' where name = 'Inter' and league = 'Serie A';
update public.teams set logo_url = 'https://r2.thesportsdb.com/images/media/team/badge/uxf0gr1742983727.png' where name = 'Juventus' and league = 'Serie A';
update public.teams set logo_url = 'https://r2.thesportsdb.com/images/media/team/badge/rwqyvs1448806608.png' where name = 'Lazio' and league = 'Serie A';
update public.teams set logo_url = 'https://r2.thesportsdb.com/images/media/team/badge/j4vznr1567365249.png' where name = 'Lecce' and league = 'Serie A';
update public.teams set logo_url = 'https://r2.thesportsdb.com/images/media/team/badge/wvspur1448806617.png' where name = 'AC Milan' and league = 'Serie A';
update public.teams set logo_url = 'https://r2.thesportsdb.com/images/media/team/badge/bxearg1603170113.png' where name = 'Monza' and league = 'Serie A';
update public.teams set logo_url = 'https://r2.thesportsdb.com/images/media/team/badge/l8qyxv1742982541.png' where name = 'Napoli' and league = 'Serie A';
update public.teams set logo_url = 'https://r2.thesportsdb.com/images/media/team/badge/6yiaxs1627406063.png' where name = 'Parma' and league = 'Serie A';
update public.teams set logo_url = 'https://r2.thesportsdb.com/images/media/team/badge/jwro2s1760820674.png' where name = 'Roma' and league = 'Serie A';
update public.teams set logo_url = 'https://r2.thesportsdb.com/images/media/team/badge/xxprty1448806802.png' where name = 'Torino' and league = 'Serie A';
update public.teams set logo_url = 'https://r2.thesportsdb.com/images/media/team/badge/vwvstr1448806811.png' where name = 'Udinese' and league = 'Serie A';
update public.teams set logo_url = 'https://r2.thesportsdb.com/images/media/team/badge/vbiget1781026964.png' where name = 'Venezia' and league = 'Serie A';
update public.teams set logo_url = 'https://r2.thesportsdb.com/images/media/team/badge/ix6q4w1678808069.png' where name = 'Angers' and league = 'Ligue 1';
update public.teams set logo_url = 'https://r2.thesportsdb.com/images/media/team/badge/lzdtbf1658753355.png' where name = 'Auxerre' and league = 'Ligue 1';
update public.teams set logo_url = 'https://r2.thesportsdb.com/images/media/team/badge/z69be41598797026.png' where name = 'Brest' and league = 'Ligue 1';
update public.teams set logo_url = 'https://r2.thesportsdb.com/images/media/team/badge/aikowk1546475003.png' where name = 'Le Havre' and league = 'Ligue 1';
update public.teams set logo_url = 'https://r2.thesportsdb.com/images/media/team/badge/3pxoum1598797195.png' where name = 'Lens' and league = 'Ligue 1';
update public.teams set logo_url = 'https://r2.thesportsdb.com/images/media/team/badge/2giize1534005340.png' where name = 'Lille' and league = 'Ligue 1';
update public.teams set logo_url = 'https://r2.thesportsdb.com/images/media/team/badge/blk9771656932845.png' where name = 'Lyon' and league = 'Ligue 1';
update public.teams set logo_url = 'https://r2.thesportsdb.com/images/media/team/badge/c6bazh1779212287.png' where name = 'Marseille' and league = 'Ligue 1';
update public.teams set logo_url = 'https://r2.thesportsdb.com/images/media/team/badge/exjf5l1678808044.png' where name = 'Monaco' and league = 'Ligue 1';
update public.teams set logo_url = 'https://r2.thesportsdb.com/images/media/team/badge/8wn9x31750879448.png' where name = 'Montpellier' and league = 'Ligue 1';
update public.teams set logo_url = 'https://r2.thesportsdb.com/images/media/team/badge/mla9x61678808018.png' where name = 'Nantes' and league = 'Ligue 1';
update public.teams set logo_url = 'https://r2.thesportsdb.com/images/media/team/badge/msy7ly1621593859.png' where name = 'Nice' and league = 'Ligue 1';
update public.teams set logo_url = 'https://r2.thesportsdb.com/images/media/team/badge/rwqrrq1473504808.png' where name = 'Paris Saint-Germain' and league = 'Ligue 1';
update public.teams set logo_url = 'https://r2.thesportsdb.com/images/media/team/badge/xcrw1b1592925946.png' where name = 'Reims' and league = 'Ligue 1';
update public.teams set logo_url = 'https://r2.thesportsdb.com/images/media/team/badge/ypturx1473504818.png' where name = 'Rennes' and league = 'Ligue 1';
update public.teams set logo_url = 'https://r2.thesportsdb.com/images/media/team/badge/m4ej831656423694.png' where name = 'Saint-Etienne' and league = 'Ligue 1';
update public.teams set logo_url = 'https://r2.thesportsdb.com/images/media/team/badge/b8k77w1766625501.png' where name = 'Strasbourg' and league = 'Ligue 1';
update public.teams set logo_url = 'https://r2.thesportsdb.com/images/media/team/badge/17eqox1688449282.png' where name = 'Toulouse' and league = 'Ligue 1';
update public.teams set logo_url = 'https://r2.thesportsdb.com/images/media/team/badge/zg9tii1755495289.png' where name = 'Ajax' and league = 'Rest of Europe';
update public.teams set logo_url = 'https://r2.thesportsdb.com/images/media/team/badge/xfsz6i1721297428.png' where name = 'PSV Eindhoven' and league = 'Rest of Europe';
update public.teams set logo_url = 'https://r2.thesportsdb.com/images/media/team/badge/uturtx1473534803.png' where name = 'Feyenoord' and league = 'Rest of Europe';
update public.teams set logo_url = 'https://r2.thesportsdb.com/images/media/team/badge/hj4kyc1781152436.png' where name = 'Benfica' and league = 'Rest of Europe';
update public.teams set logo_url = 'https://r2.thesportsdb.com/images/media/team/badge/xu47rb1628855600.png' where name = 'Porto' and league = 'Rest of Europe';
update public.teams set logo_url = 'https://r2.thesportsdb.com/images/media/team/badge/5hiuk71783137875.png' where name = 'Sporting CP' and league = 'Rest of Europe';
update public.teams set logo_url = 'https://r2.thesportsdb.com/images/media/team/badge/3uv1641758780002.png' where name = 'Celtic' and league = 'Rest of Europe';
update public.teams set logo_url = 'https://r2.thesportsdb.com/images/media/team/badge/ti24j61614290048.png' where name = 'Rangers' and league = 'Rest of Europe';
update public.teams set logo_url = 'https://r2.thesportsdb.com/images/media/team/badge/io7jk21767941298.png' where name = 'Galatasaray' and league = 'Rest of Europe';
update public.teams set logo_url = 'https://r2.thesportsdb.com/images/media/team/badge/twxxvs1448199691.png' where name = 'Fenerbahce' and league = 'Rest of Europe';
update public.teams set logo_url = 'https://r2.thesportsdb.com/images/media/team/badge/svo05k1776827439.png' where name = 'Besiktas' and league = 'Rest of Europe';
update public.teams set logo_url = 'https://r2.thesportsdb.com/images/media/team/badge/mz8y0q1771129880.png' where name = 'Club Brugge' and league = 'Rest of Europe';
update public.teams set logo_url = 'https://r2.thesportsdb.com/images/media/team/badge/auindn1771129464.png' where name = 'Anderlecht' and league = 'Rest of Europe';
update public.teams set logo_url = 'https://r2.thesportsdb.com/images/media/team/badge/nc2cua1781541639.png' where name = 'Red Bull Salzburg' and league = 'Rest of Europe';
update public.teams set logo_url = 'https://r2.thesportsdb.com/images/media/team/badge/sqrxsr1421791799.png' where name = 'Shakhtar Donetsk' and league = 'Rest of Europe';
update public.teams set logo_url = 'https://r2.thesportsdb.com/images/media/team/badge/ktbncx1781158762.png' where name = 'Dynamo Kyiv' and league = 'Rest of Europe';
update public.teams set logo_url = 'https://r2.thesportsdb.com/images/media/team/badge/l7kl4n1759252139.png' where name = 'Slavia Prague' and league = 'Rest of Europe';
update public.teams set logo_url = 'https://r2.thesportsdb.com/images/media/team/badge/j00qct1718287150.png' where name = 'Sparta Prague' and league = 'Rest of Europe';
update public.teams set logo_url = 'https://r2.thesportsdb.com/images/media/team/badge/xckasq1721291508.png' where name = 'Olympiacos' and league = 'Rest of Europe';
update public.teams set logo_url = 'https://r2.thesportsdb.com/images/media/team/badge/9mxdoo1534784569.png' where name = 'Young Boys' and league = 'Rest of Europe';
update public.teams set logo_url = 'https://r2.thesportsdb.com/images/media/team/badge/styqtr1473535513.png' where name = 'Copenhagen' and league = 'Rest of Europe';
update public.teams set logo_url = 'https://r2.thesportsdb.com/images/media/team/badge/429jzd1779940315.png' where name = 'Malmo' and league = 'Rest of Europe';
update public.teams set logo_url = 'https://r2.thesportsdb.com/images/media/team/badge/3zplhu1726167477.png' where name = 'Argentina' and league = 'International';
update public.teams set logo_url = 'https://r2.thesportsdb.com/images/media/team/badge/eylq8x1781926138.png' where name = 'Australia' and league = 'International';
update public.teams set logo_url = 'https://r2.thesportsdb.com/images/media/team/badge/874p631628721400.png' where name = 'Austria' and league = 'International';
update public.teams set logo_url = 'https://r2.thesportsdb.com/images/media/team/badge/8xlvxv1592062265.png' where name = 'Belgium' and league = 'International';
update public.teams set logo_url = 'https://r2.thesportsdb.com/images/media/team/badge/jl6dip1726167280.png' where name = 'Brazil' and league = 'International';
update public.teams set logo_url = 'https://r2.thesportsdb.com/images/media/team/badge/txqspw1455463989.png' where name = 'Cameroon' and league = 'International';
update public.teams set logo_url = 'https://r2.thesportsdb.com/images/media/team/badge/2t631f1595154867.png' where name = 'Canada' and league = 'International';
update public.teams set logo_url = 'https://r2.thesportsdb.com/images/media/team/badge/5xjsy41591988732.png' where name = 'Chile' and league = 'International';
update public.teams set logo_url = 'https://r2.thesportsdb.com/images/media/team/badge/4ymyku1691180081.png' where name = 'Colombia' and league = 'International';
update public.teams set logo_url = 'https://r2.thesportsdb.com/images/media/team/badge/bss90a1637840151.png' where name = 'Costa Rica' and league = 'International';
update public.teams set logo_url = 'https://r2.thesportsdb.com/images/media/team/badge/vvtsyu1455465317.png' where name = 'Croatia' and league = 'International';
update public.teams set logo_url = 'https://r2.thesportsdb.com/images/media/team/badge/1o0cx31654205806.png' where name = 'Czechia' and league = 'International';
update public.teams set logo_url = 'https://r2.thesportsdb.com/images/media/team/badge/e13arj1717365623.png' where name = 'Denmark' and league = 'International';
update public.teams set logo_url = 'https://r2.thesportsdb.com/images/media/team/badge/47wv2y1591989301.png' where name = 'Ecuador' and league = 'International';
update public.teams set logo_url = 'https://r2.thesportsdb.com/images/media/team/badge/uheyzo1742102234.png' where name = 'Egypt' and league = 'International';
update public.teams set logo_url = 'https://r2.thesportsdb.com/images/media/team/badge/vf5ttc1726166739.png' where name = 'England' and league = 'International';
update public.teams set logo_url = 'https://r2.thesportsdb.com/images/media/team/badge/p3n0z51726166851.png' where name = 'France' and league = 'International';
update public.teams set logo_url = 'https://r2.thesportsdb.com/images/media/team/badge/1xysi51726167152.png' where name = 'Germany' and league = 'International';
update public.teams set logo_url = 'https://r2.thesportsdb.com/images/media/team/badge/j589xw1751526124.png' where name = 'Ghana' and league = 'International';
update public.teams set logo_url = 'https://r2.thesportsdb.com/images/media/team/badge/xtxtts1455465601.png' where name = 'Greece' and league = 'International';
update public.teams set logo_url = 'https://r2.thesportsdb.com/images/media/team/badge/ihaoit1717365719.png' where name = 'Hungary' and league = 'International';
update public.teams set logo_url = 'https://r2.thesportsdb.com/images/media/team/badge/xc6kuy1742982312.png' where name = 'Iceland' and league = 'International';
update public.teams set logo_url = 'https://r2.thesportsdb.com/images/media/team/badge/fxijcp1726167035.png' where name = 'Italy' and league = 'International';
update public.teams set logo_url = 'https://r2.thesportsdb.com/images/media/team/badge/rwxuuu1455465643.png' where name = 'Ivory Coast' and league = 'International';
update public.teams set logo_url = 'https://r2.thesportsdb.com/images/media/team/badge/ffsyxz1591989843.png' where name = 'Japan' and league = 'International';
update public.teams set logo_url = 'https://r2.thesportsdb.com/images/media/team/badge/3rmosi1748525208.png' where name = 'Mexico' and league = 'International';
update public.teams set logo_url = 'https://r2.thesportsdb.com/images/media/team/badge/hbmwkj1731791275.png' where name = 'Morocco' and league = 'International';
update public.teams set logo_url = 'https://r2.thesportsdb.com/images/media/team/badge/1p0hr41593787110.png' where name = 'Netherlands' and league = 'International';
update public.teams set logo_url = 'https://r2.thesportsdb.com/images/media/team/badge/qruyxr1455466056.png' where name = 'Nigeria' and league = 'International';
update public.teams set logo_url = 'https://r2.thesportsdb.com/images/media/team/badge/gyfn811591973155.png' where name = 'Norway' and league = 'International';
update public.teams set logo_url = 'https://r2.thesportsdb.com/images/media/team/badge/unszat1529144812.png' where name = 'Peru' and league = 'International';
update public.teams set logo_url = 'https://r2.thesportsdb.com/images/media/team/badge/ttvrxy1455466076.png' where name = 'Poland' and league = 'International';
update public.teams set logo_url = 'https://r2.thesportsdb.com/images/media/team/badge/swqvpy1455466083.png' where name = 'Portugal' and league = 'International';
update public.teams set logo_url = 'https://r2.thesportsdb.com/images/media/team/badge/3vq2cl1679073105.png' where name = 'Republic of Ireland' and league = 'International';
update public.teams set logo_url = 'https://r2.thesportsdb.com/images/media/team/badge/24xwpq1594125742.png' where name = 'Saudi Arabia' and league = 'International';
update public.teams set logo_url = 'https://r2.thesportsdb.com/images/media/team/badge/3691i11552945146.png' where name = 'Scotland' and league = 'International';
update public.teams set logo_url = 'https://r2.thesportsdb.com/images/media/team/badge/slayb01780546342.png' where name = 'Senegal' and league = 'International';
update public.teams set logo_url = 'https://r2.thesportsdb.com/images/media/team/badge/oxvynb1689195538.png' where name = 'Serbia' and league = 'International';
update public.teams set logo_url = 'https://r2.thesportsdb.com/images/media/team/badge/a8nqfs1589564916.png' where name = 'South Korea' and league = 'International';
update public.teams set logo_url = 'https://r2.thesportsdb.com/images/media/team/badge/ncgqyr1726166942.png' where name = 'Spain' and league = 'International';
update public.teams set logo_url = 'https://r2.thesportsdb.com/images/media/team/badge/h5adzg1591981772.png' where name = 'Sweden' and league = 'International';
update public.teams set logo_url = 'https://r2.thesportsdb.com/images/media/team/badge/mb7yqe1717365808.png' where name = 'Switzerland' and league = 'International';
update public.teams set logo_url = 'https://r2.thesportsdb.com/images/media/team/badge/70c4oo1591982459.png' where name = 'Turkey' and league = 'International';
update public.teams set logo_url = 'https://r2.thesportsdb.com/images/media/team/badge/k36g2e1591982718.png' where name = 'Ukraine' and league = 'International';
update public.teams set logo_url = 'https://r2.thesportsdb.com/images/media/team/badge/21f0oi1597948195.png' where name = 'United States' and league = 'International';
update public.teams set logo_url = 'https://r2.thesportsdb.com/images/media/team/badge/6vjbr11726167756.png' where name = 'Uruguay' and league = 'International';
update public.teams set logo_url = 'https://r2.thesportsdb.com/images/media/team/badge/pdayn21591983222.png' where name = 'Wales' and league = 'International';

grant select on public.teams to authenticated;
